apiVersion: v1
kind: Service
metadata:
  name: devops-ci-cd
  namespace: devops-ci-cd
spec:
  type: NodePort
  selector:
    app: devops-ci-cd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080